# Site settings
title: migration.fm
description: "日夜Salesforceと格闘しながらサービスを開発しているエンジニアが話す Salesforce Developer 向けのPodcastです。"
subtitle: "Salesforce Developer 向け Podcast migration.fm #migrationfm"
squareLogo: "http://i1.sndcdn.com/avatars-000223269201-7h2ox0-original.jpg"
managerName: migration.fm
managerEmail: migrationfm@gmail.com
copyright: "&#x2117; &amp; &#xA9; 2016"
keywords: Salesforce, Podcast
baseurl: "/"
url: "http://migration.fm"
lang: ja
timezone: JPN
ellipsis: "…"

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
gems:
  - jekyll-paginate
  - jekyll-sitemap

# author info
# add your appropriate info here
author: Akira.Kuratani
bio: Salesforce Developer at TeamSpirit Inc.
email: migrationfm@gmail.com
email_md5: 0f5a90aa72eccd0071a7dae1187dac9f # md5 hash of your email
twitter_username: migrationfm
twitter_hashtag: migrationfm
github_username: kuratani
rss_url: http://migration.fm/feed.xml
itunes_url: https://itunes.apple.com/jp/podcast/migration.fm/id1111956465
andriod_url: http://www.subscribeonandroid.com/migration.fm/feed.xml

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
